In [1]:
import pandas as pd
import numpy as np

In [26]:
dataset = pd.read_csv('train.csv')
dataset['FamilySize'] = dataset['SibSp'] + dataset['Parch']
print(dataset.head())




   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  FamilySize  
0      0         A/5 21171   7.2500   NaN        S           1  
1      0          PC 17599  71.2833   C85        C           1  
2      0  STON/O2. 3101282   7.9250   NaN        S           0  
3      0            113803  53.1000  C123        S          

In [55]:
feature_columns = [2,4,5,9,12]
dp = ['Survived']
X = dataset.iloc[:,feature_columns].values
y = dataset.iloc[:,1].values

print(X)

[[3 'male' 22.0 7.25 1]
 [1 'female' 38.0 71.2833 1]
 [3 'female' 26.0 7.925 0]
 ...
 [3 'female' nan 23.45 3]
 [1 'male' 26.0 30.0 0]
 [3 'male' 32.0 7.75 0]]


In [ ]:
print(y)

In [56]:
missing_values = dataset.isnull().sum()
print(missing_values)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
FamilySize       0
dtype: int64


Handling Missing Values

In [57]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,2:3])
X[:,2:3] = imputer.transform(X[:,2:3])


In [58]:
print(X)

[[3 'male' 22.0 7.25 1]
 [1 'female' 38.0 71.2833 1]
 [3 'female' 26.0 7.925 0]
 ...
 [3 'female' 29.69911764705882 23.45 3]
 [1 'male' 26.0 30.0 0]
 [3 'male' 32.0 7.75 0]]


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

Encoding


In [59]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
X[:,1] = label_encoder.fit_transform(X[:,1])
# Print the first few rows of X and y after label encoding
print("X (after label encoding):")
print(X[:5])  # Print the first 5 rows of X
print("y:")
print(y[:5])  # Print the first 5 rows of y
len(X)

X (after label encoding):
[[3 1 22.0 7.25 1]
 [1 0 38.0 71.2833 1]
 [3 0 26.0 7.925 0]
 [1 0 35.0 53.1 1]
 [3 1 35.0 8.05 0]]
y:
[0 1 1 1 0]


891

In [60]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=1)



In [61]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p =2)  #default neighors 5
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

Making the Confusion Matrix

In [63]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[88 18]
 [29 44]]


0.7374301675977654

In [36]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [37]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[91 15]
 [25 48]]


0.776536312849162